version: "3.3"

services:
  php-8.1:
    build:
    container_name: php-8.1
    environment:
      uid: ${UID}
    user: ${UID}
    ports:
      - "3000:3000"
    volumes:
      -   ../:/var/www/html
    command: /bin/sh -c "php -S 0.0.0.0:3000 -t public"